- name: Install nginx
  become: true
  yum:
    name: nginx
    state: present

- name: enable service nginx
  become: true
  systemd:
    name: nginx
    enabled: yes
    masked: no

- name: start service nginx
  become: true
  systemd:
    state: started
    name: nginx
